#We have to create a dataframe that has data from both the test set and train set, so we will read both sets
#and bind them together.

#Assuming the working directory is set to the "UC HAR Dataset" folder

test<-read.table("./test/X_test.txt")
train<-read.table("./train/X_train.txt")
features<-read.table("features.txt")

#We had read both the datasets and feature names

colNames(test)<-features$V2
colNames(train)<-features$V2

#We gave column names to each column of the test and train data set

test_label<-read.table("./test/y_test.txt")
train_label<-read.table("./train/y_train.txt")

#We read the corresponding test and train labels which give us the activity 1,2,3,4,5or6.

test_subject<-read.table("./test/subject_test.txt")
train_subject<-read.table("./train/subject_train.txt")

#We read the corresponding test subject numbers (1-30) for the test and train dataset

m<-grep("mean",names(test))
s<-grep("std",names(train))

#We get the position of the mean and standard deviation values in the dataset

new_test<-test[,c(m,s)]
new_train<-train[,c(m,s)]

#We make new_test and new_train s.t. it only contains mean and std values

test_activity<-data.frame()
for(x in 1:nrow(test_label)){
                 if(test_label[x,1]==1) test_activity[x,1]="WALKING"
                 if(test_label[x,1]==2) test_activity[x,1]="WALKING_UPSTAIRS"
                 if(test_label[x,1]==3) test_activity[x,1]="WALKING_DOWNSTAIRS"
                 if(test_label[x,1]==4) test_activity[x,1]="SITTING"
                 if(test_label[x,1]==5) test_activity[x,1]="STANDING"
                 if(test_label[x,1]==6) test_activity[x,1]="LAYING"
             }
train_activity<-data.frame()
for(x in 1:nrow(train_label)){
  if(train_label[x,1]==1) train_activity[x,1]="WALKING"
  if(train_label[x,1]==2) train_activity[x,1]="WALKING_UPSTAIRS"
  if(train_label[x,1]==3) train_activity[x,1]="WALKING_DOWNSTAIRS"
  if(train_label[x,1]==4) train_activity[x,1]="SITTING"
  if(train_label[x,1]==5) train_activity[x,1]="STANDING"
  if(train_label[x,1]==6) train_activity[x,1]="LAYING"
}

#We changed labels 1-6 to activities

final_train<-cbind(train_subject,new_train,train_activity)
final_test<-cbind(test_subject,new_test,test_activity)

#We bind the test(train) subject number, the test(train) dataset and test(train) activity set by the columns

result<-rbind(final_test,final_train)

#The resulting dataset can be generated by binding test set and train set by the columns

names(result)[1]<-"Subject_Number"
names(result)[81]<-"Activity"

#changing the column names of the columns of subject and activity columns

write.table(result,file = "result.txt",row.names = FALSE)

#Finally we write the dataset into a txt file
